/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFastEndpointsErrorResponseFromDiscriminatorValue, createServerSharedModelsApiResponseOfGetWorkflowByIdResponseDtoFromDiscriminatorValue, type FastEndpointsErrorResponse, type ServerSharedModelsApiResponseOfGetWorkflowByIdResponseDto } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /workflow/{id}
 */
export interface WorkflowItemRequestBuilder extends BaseRequestBuilder<WorkflowItemRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ServerSharedModelsApiResponseOfGetWorkflowByIdResponseDto>}
     * @throws {FastEndpointsErrorResponse} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ServerSharedModelsApiResponseOfGetWorkflowByIdResponseDto | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WorkflowItemRequestBuilderUriTemplate = "{+baseurl}/workflow/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WorkflowItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WorkflowItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createFastEndpointsErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createServerSharedModelsApiResponseOfGetWorkflowByIdResponseDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
