/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createServerSocialNetworkSimulatorEndPointsWebHoooksMessageResponseFromDiscriminatorValue, serializeServerSocialNetworkSimulatorEndPointsWebHoooksMessageRequest, serializeServerSocialNetworkSimulatorEndPointsWebHoooksMessageResponse, type ServerSocialNetworkSimulatorEndPointsWebHoooksMessageRequest, type ServerSocialNetworkSimulatorEndPointsWebHoooksMessageResponse } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /simulator/webhooks/message
 */
export interface MessageRequestBuilder extends BaseRequestBuilder<MessageRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ServerSocialNetworkSimulatorEndPointsWebHoooksMessageResponse>}
     */
     post(body: ServerSocialNetworkSimulatorEndPointsWebHoooksMessageRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ServerSocialNetworkSimulatorEndPointsWebHoooksMessageResponse | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ServerSocialNetworkSimulatorEndPointsWebHoooksMessageRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const MessageRequestBuilderUriTemplate = "{+baseurl}/simulator/webhooks/message";
/**
 * Metadata for all the requests in the request builder.
 */
export const MessageRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: MessageRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createServerSocialNetworkSimulatorEndPointsWebHoooksMessageResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeServerSocialNetworkSimulatorEndPointsWebHoooksMessageRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
