/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { MessageRequestBuilderRequestsMetadata, type MessageRequestBuilder } from './message/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /simulator/webhooks
 */
export interface WebhooksRequestBuilder extends BaseRequestBuilder<WebhooksRequestBuilder> {
    /**
     * The message property
     */
    get message(): MessageRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WebhooksRequestBuilderUriTemplate = "{+baseurl}/simulator/webhooks";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WebhooksRequestBuilderNavigationMetadata: Record<Exclude<keyof WebhooksRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    message: {
        requestsMetadata: MessageRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
