/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFastEndpointsErrorResponseFromDiscriminatorValue, createServerSharedModelsApiResponseOfGetHubsResponseFromDiscriminatorValue, type FastEndpointsErrorResponse, type ServerSharedModelsApiResponseOfGetHubsResponse } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /hub/all
 */
export interface AllRequestBuilder extends BaseRequestBuilder<AllRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ServerSharedModelsApiResponseOfGetHubsResponse>}
     * @throws {FastEndpointsErrorResponse} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<AllRequestBuilderGetQueryParameters> | undefined) : Promise<ServerSharedModelsApiResponseOfGetHubsResponse | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<AllRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
export interface AllRequestBuilderGetQueryParameters {
    tenantId?: string;
}
/**
 * Uri template for the request builder.
 */
export const AllRequestBuilderUriTemplate = "{+baseurl}/hub/all?tenantId={tenantId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const AllRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: AllRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createFastEndpointsErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createServerSharedModelsApiResponseOfGetHubsResponseFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
