/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithTenantItemRequestBuilder, WithTenantItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /streams
 */
export interface StreamsRequestBuilder extends BaseRequestBuilder<StreamsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.streams.item collection
     * @param tenantId Unique identifier of the item
     * @returns {WithTenantItemRequestBuilder}
     */
     byTenantId(tenantId: string) : WithTenantItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const StreamsRequestBuilderUriTemplate = "{+baseurl}/streams";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const StreamsRequestBuilderNavigationMetadata: Record<Exclude<keyof StreamsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byTenantId: {
        requestsMetadata: WithTenantItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["tenantId"],
    },
};
/* tslint:enable */
/* eslint-enable */
