/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AllRequestBuilderRequestsMetadata, type AllRequestBuilder } from './all/index.js';
// @ts-ignore
import { type WithPlatformItemRequestBuilder, WithPlatformItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /hub
 */
export interface HubRequestBuilder extends BaseRequestBuilder<HubRequestBuilder> {
    /**
     * The all property
     */
    get all(): AllRequestBuilder;
    /**
     * Gets an item from the ApiSdk.hub.item collection
     * @param platformId Unique identifier of the item
     * @returns {WithPlatformItemRequestBuilder}
     */
     byPlatformId(platformId: string) : WithPlatformItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const HubRequestBuilderUriTemplate = "{+baseurl}/hub";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const HubRequestBuilderNavigationMetadata: Record<Exclude<keyof HubRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byPlatformId: {
        requestsMetadata: WithPlatformItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["platformId"],
    },
    all: {
        requestsMetadata: AllRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
