/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFastEndpointsErrorResponseFromDiscriminatorValue, createServerSharedModelsApiResponseOfAssignWorkflowToUserResponseDtoFromDiscriminatorValue, serializeServerSharedModelsApiResponseOfAssignWorkflowToUserResponseDto, serializeServerWorkflowsContractsCommandsAssignWorkflowToUserCommand, type FastEndpointsErrorResponse, type ServerSharedModelsApiResponseOfAssignWorkflowToUserResponseDto, type ServerWorkflowsContractsCommandsAssignWorkflowToUserCommand } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /workflow/assign-workflow-user
 */
export interface AssignWorkflowUserRequestBuilder extends BaseRequestBuilder<AssignWorkflowUserRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ServerSharedModelsApiResponseOfAssignWorkflowToUserResponseDto>}
     * @throws {FastEndpointsErrorResponse} error when the service returns a 400 status code
     */
     post(body: ServerWorkflowsContractsCommandsAssignWorkflowToUserCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ServerSharedModelsApiResponseOfAssignWorkflowToUserResponseDto | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ServerWorkflowsContractsCommandsAssignWorkflowToUserCommand, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const AssignWorkflowUserRequestBuilderUriTemplate = "{+baseurl}/workflow/assign-workflow-user";
/**
 * Metadata for all the requests in the request builder.
 */
export const AssignWorkflowUserRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: AssignWorkflowUserRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createFastEndpointsErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createServerSharedModelsApiResponseOfAssignWorkflowToUserResponseDtoFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeServerWorkflowsContractsCommandsAssignWorkflowToUserCommand,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
