/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WorldRequestBuilder, WorldRequestBuilderRequestsMetadata } from './world/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /hello
 */
export interface HelloRequestBuilder extends BaseRequestBuilder<HelloRequestBuilder> {
    /**
     * The world property
     */
    get world(): WorldRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const HelloRequestBuilderUriTemplate = "{+baseurl}/hello";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const HelloRequestBuilderNavigationMetadata: Record<Exclude<keyof HelloRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    world: {
        requestsMetadata: WorldRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
