/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FastEndpointsErrorResponse_errors}
 */
// @ts-ignore
export function createFastEndpointsErrorResponse_errorsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFastEndpointsErrorResponse_errors;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FastEndpointsErrorResponse}
 */
// @ts-ignore
export function createFastEndpointsErrorResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFastEndpointsErrorResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerNotificationContractsMessageDtosGetMessageResponseDto}
 */
// @ts-ignore
export function createServerNotificationContractsMessageDtosGetMessageResponseDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerNotificationContractsMessageDtosGetMessageResponseDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerNotificationContractsMessageQueriesGetMessageQuery}
 */
// @ts-ignore
export function createServerNotificationContractsMessageQueriesGetMessageQueryFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerNotificationContractsMessageQueriesGetMessageQuery;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerSharedModelsApiResponseOfAddHubResponse}
 */
// @ts-ignore
export function createServerSharedModelsApiResponseOfAddHubResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerSharedModelsApiResponseOfAddHubResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerSharedModelsApiResponseOfAddWorkflowResponseDto}
 */
// @ts-ignore
export function createServerSharedModelsApiResponseOfAddWorkflowResponseDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerSharedModelsApiResponseOfAddWorkflowResponseDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerSharedModelsApiResponseOfAssignWorkflowToUserResponseDto}
 */
// @ts-ignore
export function createServerSharedModelsApiResponseOfAssignWorkflowToUserResponseDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerSharedModelsApiResponseOfAssignWorkflowToUserResponseDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerSharedModelsApiResponseOfEditWorkflowResponseDto}
 */
// @ts-ignore
export function createServerSharedModelsApiResponseOfEditWorkflowResponseDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerSharedModelsApiResponseOfEditWorkflowResponseDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerSharedModelsApiResponseOfGetAllowedWorkflowsByUserResponseDto}
 */
// @ts-ignore
export function createServerSharedModelsApiResponseOfGetAllowedWorkflowsByUserResponseDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerSharedModelsApiResponseOfGetAllowedWorkflowsByUserResponseDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerSharedModelsApiResponseOfGetHubsResponse}
 */
// @ts-ignore
export function createServerSharedModelsApiResponseOfGetHubsResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerSharedModelsApiResponseOfGetHubsResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerSharedModelsApiResponseOfGetKanbanCardsByColumnIdResponseDto}
 */
// @ts-ignore
export function createServerSharedModelsApiResponseOfGetKanbanCardsByColumnIdResponseDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerSharedModelsApiResponseOfGetKanbanCardsByColumnIdResponseDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerSharedModelsApiResponseOfGetWorkflowByIdResponseDto}
 */
// @ts-ignore
export function createServerSharedModelsApiResponseOfGetWorkflowByIdResponseDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerSharedModelsApiResponseOfGetWorkflowByIdResponseDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerSharedModelsApiResponseOfGetWorkflowsResponseDto}
 */
// @ts-ignore
export function createServerSharedModelsApiResponseOfGetWorkflowsResponseDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerSharedModelsApiResponseOfGetWorkflowsResponseDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerSocialNetworkContractsHubsAddHubResponse}
 */
// @ts-ignore
export function createServerSocialNetworkContractsHubsAddHubResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerSocialNetworkContractsHubsAddHubResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerSocialNetworkContractsHubsGetHubsResponse}
 */
// @ts-ignore
export function createServerSocialNetworkContractsHubsGetHubsResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerSocialNetworkContractsHubsGetHubsResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerSocialNetworkContractsHubsHubItem}
 */
// @ts-ignore
export function createServerSocialNetworkContractsHubsHubItemFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerSocialNetworkContractsHubsHubItem;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerSocialNetworkEndPointsHubsRequestsAddHubRequest}
 */
// @ts-ignore
export function createServerSocialNetworkEndPointsHubsRequestsAddHubRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerSocialNetworkEndPointsHubsRequestsAddHubRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerSocialNetworkSimulatorEndPointsWebHoooksMessageRequest}
 */
// @ts-ignore
export function createServerSocialNetworkSimulatorEndPointsWebHoooksMessageRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerSocialNetworkSimulatorEndPointsWebHoooksMessageRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerSocialNetworkSimulatorEndPointsWebHoooksMessageResponse}
 */
// @ts-ignore
export function createServerSocialNetworkSimulatorEndPointsWebHoooksMessageResponseFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerSocialNetworkSimulatorEndPointsWebHoooksMessageResponse;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerWorkflowsContractsCardsCardContentTypesICardContentType}
 */
// @ts-ignore
export function createServerWorkflowsContractsCardsCardContentTypesICardContentTypeFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerWorkflowsContractsCardsCardContentTypesICardContentType;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerWorkflowsContractsCardsKanbanCardDto}
 */
// @ts-ignore
export function createServerWorkflowsContractsCardsKanbanCardDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerWorkflowsContractsCardsKanbanCardDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerWorkflowsContractsCommandsAddWorkflowCommand}
 */
// @ts-ignore
export function createServerWorkflowsContractsCommandsAddWorkflowCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerWorkflowsContractsCommandsAddWorkflowCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerWorkflowsContractsCommandsAssignWorkflowToUserCommand}
 */
// @ts-ignore
export function createServerWorkflowsContractsCommandsAssignWorkflowToUserCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerWorkflowsContractsCommandsAssignWorkflowToUserCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerWorkflowsContractsCommandsEditWorkflowCommand}
 */
// @ts-ignore
export function createServerWorkflowsContractsCommandsEditWorkflowCommandFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerWorkflowsContractsCommandsEditWorkflowCommand;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerWorkflowsContractsDtosAddWorkflowResponseDto}
 */
// @ts-ignore
export function createServerWorkflowsContractsDtosAddWorkflowResponseDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerWorkflowsContractsDtosAddWorkflowResponseDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerWorkflowsContractsDtosAllowedWorkflowDto}
 */
// @ts-ignore
export function createServerWorkflowsContractsDtosAllowedWorkflowDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerWorkflowsContractsDtosAllowedWorkflowDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerWorkflowsContractsDtosAssignWorkflowToUserResponseDto}
 */
// @ts-ignore
export function createServerWorkflowsContractsDtosAssignWorkflowToUserResponseDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerWorkflowsContractsDtosAssignWorkflowToUserResponseDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerWorkflowsContractsDtosColumnItemDto}
 */
// @ts-ignore
export function createServerWorkflowsContractsDtosColumnItemDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerWorkflowsContractsDtosColumnItemDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerWorkflowsContractsDtosColumnItemResponseDto}
 */
// @ts-ignore
export function createServerWorkflowsContractsDtosColumnItemResponseDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerWorkflowsContractsDtosColumnItemResponseDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerWorkflowsContractsDtosEditColumnItemDto}
 */
// @ts-ignore
export function createServerWorkflowsContractsDtosEditColumnItemDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerWorkflowsContractsDtosEditColumnItemDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerWorkflowsContractsDtosEditWorkflowResponseDto}
 */
// @ts-ignore
export function createServerWorkflowsContractsDtosEditWorkflowResponseDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerWorkflowsContractsDtosEditWorkflowResponseDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerWorkflowsContractsDtosGetAllowedWorkflowsByUserResponseDto}
 */
// @ts-ignore
export function createServerWorkflowsContractsDtosGetAllowedWorkflowsByUserResponseDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerWorkflowsContractsDtosGetAllowedWorkflowsByUserResponseDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerWorkflowsContractsDtosGetKanbanCardsByColumnIdResponseDto}
 */
// @ts-ignore
export function createServerWorkflowsContractsDtosGetKanbanCardsByColumnIdResponseDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerWorkflowsContractsDtosGetKanbanCardsByColumnIdResponseDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerWorkflowsContractsDtosGetWorkflowByIdResponseDto}
 */
// @ts-ignore
export function createServerWorkflowsContractsDtosGetWorkflowByIdResponseDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerWorkflowsContractsDtosGetWorkflowByIdResponseDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerWorkflowsContractsDtosGetWorkflowsResponseDto}
 */
// @ts-ignore
export function createServerWorkflowsContractsDtosGetWorkflowsResponseDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerWorkflowsContractsDtosGetWorkflowsResponseDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerWorkflowsContractsDtosWorkflowColumnDto}
 */
// @ts-ignore
export function createServerWorkflowsContractsDtosWorkflowColumnDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerWorkflowsContractsDtosWorkflowColumnDto;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {ServerWorkflowsContractsDtosWorkflowDto}
 */
// @ts-ignore
export function createServerWorkflowsContractsDtosWorkflowDtoFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoServerWorkflowsContractsDtosWorkflowDto;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFastEndpointsErrorResponse(fastEndpointsErrorResponse: Partial<FastEndpointsErrorResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "errors": n => { fastEndpointsErrorResponse.errors = n.getObjectValue<FastEndpointsErrorResponse_errors>(createFastEndpointsErrorResponse_errorsFromDiscriminatorValue); },
        "message": n => { fastEndpointsErrorResponse.messageEscaped = n.getStringValue() ?? "One or more errors occurred!"; },
        "statusCode": n => { fastEndpointsErrorResponse.statusCode = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFastEndpointsErrorResponse_errors(fastEndpointsErrorResponse_errors: Partial<FastEndpointsErrorResponse_errors> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerNotificationContractsMessageDtosGetMessageResponseDto(serverNotificationContractsMessageDtosGetMessageResponseDto: Partial<ServerNotificationContractsMessageDtosGetMessageResponseDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "text": n => { serverNotificationContractsMessageDtosGetMessageResponseDto.text = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerNotificationContractsMessageQueriesGetMessageQuery(serverNotificationContractsMessageQueriesGetMessageQuery: Partial<ServerNotificationContractsMessageQueriesGetMessageQuery> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "text": n => { serverNotificationContractsMessageQueriesGetMessageQuery.text = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerSharedModelsApiResponseOfAddHubResponse(serverSharedModelsApiResponseOfAddHubResponse: Partial<ServerSharedModelsApiResponseOfAddHubResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { serverSharedModelsApiResponseOfAddHubResponse.data = n.getObjectValue<ServerSocialNetworkContractsHubsAddHubResponse>(createServerSocialNetworkContractsHubsAddHubResponseFromDiscriminatorValue); },
        "errors": n => { serverSharedModelsApiResponseOfAddHubResponse.errors = n.getCollectionOfPrimitiveValues<string>(); },
        "isSuccess": n => { serverSharedModelsApiResponseOfAddHubResponse.isSuccess = n.getBooleanValue(); },
        "message": n => { serverSharedModelsApiResponseOfAddHubResponse.message = n.getStringValue(); },
        "validationErrors": n => { serverSharedModelsApiResponseOfAddHubResponse.validationErrors = n.getCollectionOfPrimitiveValues<string>(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerSharedModelsApiResponseOfAddWorkflowResponseDto(serverSharedModelsApiResponseOfAddWorkflowResponseDto: Partial<ServerSharedModelsApiResponseOfAddWorkflowResponseDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { serverSharedModelsApiResponseOfAddWorkflowResponseDto.data = n.getObjectValue<ServerWorkflowsContractsDtosAddWorkflowResponseDto>(createServerWorkflowsContractsDtosAddWorkflowResponseDtoFromDiscriminatorValue); },
        "errors": n => { serverSharedModelsApiResponseOfAddWorkflowResponseDto.errors = n.getCollectionOfPrimitiveValues<string>(); },
        "isSuccess": n => { serverSharedModelsApiResponseOfAddWorkflowResponseDto.isSuccess = n.getBooleanValue(); },
        "message": n => { serverSharedModelsApiResponseOfAddWorkflowResponseDto.message = n.getStringValue(); },
        "validationErrors": n => { serverSharedModelsApiResponseOfAddWorkflowResponseDto.validationErrors = n.getCollectionOfPrimitiveValues<string>(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerSharedModelsApiResponseOfAssignWorkflowToUserResponseDto(serverSharedModelsApiResponseOfAssignWorkflowToUserResponseDto: Partial<ServerSharedModelsApiResponseOfAssignWorkflowToUserResponseDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { serverSharedModelsApiResponseOfAssignWorkflowToUserResponseDto.data = n.getObjectValue<ServerWorkflowsContractsDtosAssignWorkflowToUserResponseDto>(createServerWorkflowsContractsDtosAssignWorkflowToUserResponseDtoFromDiscriminatorValue); },
        "errors": n => { serverSharedModelsApiResponseOfAssignWorkflowToUserResponseDto.errors = n.getCollectionOfPrimitiveValues<string>(); },
        "isSuccess": n => { serverSharedModelsApiResponseOfAssignWorkflowToUserResponseDto.isSuccess = n.getBooleanValue(); },
        "message": n => { serverSharedModelsApiResponseOfAssignWorkflowToUserResponseDto.message = n.getStringValue(); },
        "validationErrors": n => { serverSharedModelsApiResponseOfAssignWorkflowToUserResponseDto.validationErrors = n.getCollectionOfPrimitiveValues<string>(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerSharedModelsApiResponseOfEditWorkflowResponseDto(serverSharedModelsApiResponseOfEditWorkflowResponseDto: Partial<ServerSharedModelsApiResponseOfEditWorkflowResponseDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { serverSharedModelsApiResponseOfEditWorkflowResponseDto.data = n.getObjectValue<ServerWorkflowsContractsDtosEditWorkflowResponseDto>(createServerWorkflowsContractsDtosEditWorkflowResponseDtoFromDiscriminatorValue); },
        "errors": n => { serverSharedModelsApiResponseOfEditWorkflowResponseDto.errors = n.getCollectionOfPrimitiveValues<string>(); },
        "isSuccess": n => { serverSharedModelsApiResponseOfEditWorkflowResponseDto.isSuccess = n.getBooleanValue(); },
        "message": n => { serverSharedModelsApiResponseOfEditWorkflowResponseDto.message = n.getStringValue(); },
        "validationErrors": n => { serverSharedModelsApiResponseOfEditWorkflowResponseDto.validationErrors = n.getCollectionOfPrimitiveValues<string>(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerSharedModelsApiResponseOfGetAllowedWorkflowsByUserResponseDto(serverSharedModelsApiResponseOfGetAllowedWorkflowsByUserResponseDto: Partial<ServerSharedModelsApiResponseOfGetAllowedWorkflowsByUserResponseDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { serverSharedModelsApiResponseOfGetAllowedWorkflowsByUserResponseDto.data = n.getObjectValue<ServerWorkflowsContractsDtosGetAllowedWorkflowsByUserResponseDto>(createServerWorkflowsContractsDtosGetAllowedWorkflowsByUserResponseDtoFromDiscriminatorValue); },
        "errors": n => { serverSharedModelsApiResponseOfGetAllowedWorkflowsByUserResponseDto.errors = n.getCollectionOfPrimitiveValues<string>(); },
        "isSuccess": n => { serverSharedModelsApiResponseOfGetAllowedWorkflowsByUserResponseDto.isSuccess = n.getBooleanValue(); },
        "message": n => { serverSharedModelsApiResponseOfGetAllowedWorkflowsByUserResponseDto.message = n.getStringValue(); },
        "validationErrors": n => { serverSharedModelsApiResponseOfGetAllowedWorkflowsByUserResponseDto.validationErrors = n.getCollectionOfPrimitiveValues<string>(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerSharedModelsApiResponseOfGetHubsResponse(serverSharedModelsApiResponseOfGetHubsResponse: Partial<ServerSharedModelsApiResponseOfGetHubsResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { serverSharedModelsApiResponseOfGetHubsResponse.data = n.getObjectValue<ServerSocialNetworkContractsHubsGetHubsResponse>(createServerSocialNetworkContractsHubsGetHubsResponseFromDiscriminatorValue); },
        "errors": n => { serverSharedModelsApiResponseOfGetHubsResponse.errors = n.getCollectionOfPrimitiveValues<string>(); },
        "isSuccess": n => { serverSharedModelsApiResponseOfGetHubsResponse.isSuccess = n.getBooleanValue(); },
        "message": n => { serverSharedModelsApiResponseOfGetHubsResponse.message = n.getStringValue(); },
        "validationErrors": n => { serverSharedModelsApiResponseOfGetHubsResponse.validationErrors = n.getCollectionOfPrimitiveValues<string>(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerSharedModelsApiResponseOfGetKanbanCardsByColumnIdResponseDto(serverSharedModelsApiResponseOfGetKanbanCardsByColumnIdResponseDto: Partial<ServerSharedModelsApiResponseOfGetKanbanCardsByColumnIdResponseDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { serverSharedModelsApiResponseOfGetKanbanCardsByColumnIdResponseDto.data = n.getObjectValue<ServerWorkflowsContractsDtosGetKanbanCardsByColumnIdResponseDto>(createServerWorkflowsContractsDtosGetKanbanCardsByColumnIdResponseDtoFromDiscriminatorValue); },
        "errors": n => { serverSharedModelsApiResponseOfGetKanbanCardsByColumnIdResponseDto.errors = n.getCollectionOfPrimitiveValues<string>(); },
        "isSuccess": n => { serverSharedModelsApiResponseOfGetKanbanCardsByColumnIdResponseDto.isSuccess = n.getBooleanValue(); },
        "message": n => { serverSharedModelsApiResponseOfGetKanbanCardsByColumnIdResponseDto.message = n.getStringValue(); },
        "validationErrors": n => { serverSharedModelsApiResponseOfGetKanbanCardsByColumnIdResponseDto.validationErrors = n.getCollectionOfPrimitiveValues<string>(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerSharedModelsApiResponseOfGetWorkflowByIdResponseDto(serverSharedModelsApiResponseOfGetWorkflowByIdResponseDto: Partial<ServerSharedModelsApiResponseOfGetWorkflowByIdResponseDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { serverSharedModelsApiResponseOfGetWorkflowByIdResponseDto.data = n.getObjectValue<ServerWorkflowsContractsDtosGetWorkflowByIdResponseDto>(createServerWorkflowsContractsDtosGetWorkflowByIdResponseDtoFromDiscriminatorValue); },
        "errors": n => { serverSharedModelsApiResponseOfGetWorkflowByIdResponseDto.errors = n.getCollectionOfPrimitiveValues<string>(); },
        "isSuccess": n => { serverSharedModelsApiResponseOfGetWorkflowByIdResponseDto.isSuccess = n.getBooleanValue(); },
        "message": n => { serverSharedModelsApiResponseOfGetWorkflowByIdResponseDto.message = n.getStringValue(); },
        "validationErrors": n => { serverSharedModelsApiResponseOfGetWorkflowByIdResponseDto.validationErrors = n.getCollectionOfPrimitiveValues<string>(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerSharedModelsApiResponseOfGetWorkflowsResponseDto(serverSharedModelsApiResponseOfGetWorkflowsResponseDto: Partial<ServerSharedModelsApiResponseOfGetWorkflowsResponseDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "data": n => { serverSharedModelsApiResponseOfGetWorkflowsResponseDto.data = n.getObjectValue<ServerWorkflowsContractsDtosGetWorkflowsResponseDto>(createServerWorkflowsContractsDtosGetWorkflowsResponseDtoFromDiscriminatorValue); },
        "errors": n => { serverSharedModelsApiResponseOfGetWorkflowsResponseDto.errors = n.getCollectionOfPrimitiveValues<string>(); },
        "isSuccess": n => { serverSharedModelsApiResponseOfGetWorkflowsResponseDto.isSuccess = n.getBooleanValue(); },
        "message": n => { serverSharedModelsApiResponseOfGetWorkflowsResponseDto.message = n.getStringValue(); },
        "validationErrors": n => { serverSharedModelsApiResponseOfGetWorkflowsResponseDto.validationErrors = n.getCollectionOfPrimitiveValues<string>(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerSocialNetworkContractsHubsAddHubResponse(serverSocialNetworkContractsHubsAddHubResponse: Partial<ServerSocialNetworkContractsHubsAddHubResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { serverSocialNetworkContractsHubsAddHubResponse.id = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerSocialNetworkContractsHubsGetHubsResponse(serverSocialNetworkContractsHubsGetHubsResponse: Partial<ServerSocialNetworkContractsHubsGetHubsResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "items": n => { serverSocialNetworkContractsHubsGetHubsResponse.items = n.getCollectionOfObjectValues<ServerSocialNetworkContractsHubsHubItem>(createServerSocialNetworkContractsHubsHubItemFromDiscriminatorValue); },
        "tenantId": n => { serverSocialNetworkContractsHubsGetHubsResponse.tenantId = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerSocialNetworkContractsHubsHubItem(serverSocialNetworkContractsHubsHubItem: Partial<ServerSocialNetworkContractsHubsHubItem> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "hubId": n => { serverSocialNetworkContractsHubsHubItem.hubId = n.getStringValue(); },
        "phoneNumber": n => { serverSocialNetworkContractsHubsHubItem.phoneNumber = n.getStringValue(); },
        "platformId": n => { serverSocialNetworkContractsHubsHubItem.platformId = n.getStringValue(); },
        "status": n => { serverSocialNetworkContractsHubsHubItem.status = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerSocialNetworkEndPointsHubsRequestsAddHubRequest(serverSocialNetworkEndPointsHubsRequestsAddHubRequest: Partial<ServerSocialNetworkEndPointsHubsRequestsAddHubRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "name": n => { serverSocialNetworkEndPointsHubsRequestsAddHubRequest.name = n.getStringValue(); },
        "phoneNumber": n => { serverSocialNetworkEndPointsHubsRequestsAddHubRequest.phoneNumber = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerSocialNetworkSimulatorEndPointsWebHoooksMessageRequest(serverSocialNetworkSimulatorEndPointsWebHoooksMessageRequest: Partial<ServerSocialNetworkSimulatorEndPointsWebHoooksMessageRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "message": n => { serverSocialNetworkSimulatorEndPointsWebHoooksMessageRequest.message = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerSocialNetworkSimulatorEndPointsWebHoooksMessageResponse(serverSocialNetworkSimulatorEndPointsWebHoooksMessageResponse: Partial<ServerSocialNetworkSimulatorEndPointsWebHoooksMessageResponse> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "status": n => { serverSocialNetworkSimulatorEndPointsWebHoooksMessageResponse.status = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerWorkflowsContractsCardsCardContentTypesICardContentType(serverWorkflowsContractsCardsCardContentTypesICardContentType: Partial<ServerWorkflowsContractsCardsCardContentTypesICardContentType> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "contentType": n => { serverWorkflowsContractsCardsCardContentTypesICardContentType.contentType = n.getStringValue(); },
        "hubId": n => { serverWorkflowsContractsCardsCardContentTypesICardContentType.hubId = n.getStringValue(); },
        "platformId": n => { serverWorkflowsContractsCardsCardContentTypesICardContentType.platformId = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerWorkflowsContractsCardsKanbanCardDto(serverWorkflowsContractsCardsKanbanCardDto: Partial<ServerWorkflowsContractsCardsKanbanCardDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "columnId": n => { serverWorkflowsContractsCardsKanbanCardDto.columnId = n.getStringValue(); },
        "content": n => { serverWorkflowsContractsCardsKanbanCardDto.content = n.getObjectValue<ServerWorkflowsContractsCardsCardContentTypesICardContentType>(createServerWorkflowsContractsCardsCardContentTypesICardContentTypeFromDiscriminatorValue); },
        "id": n => { serverWorkflowsContractsCardsKanbanCardDto.id = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerWorkflowsContractsCommandsAddWorkflowCommand(serverWorkflowsContractsCommandsAddWorkflowCommand: Partial<ServerWorkflowsContractsCommandsAddWorkflowCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "columns": n => { serverWorkflowsContractsCommandsAddWorkflowCommand.columns = n.getCollectionOfObjectValues<ServerWorkflowsContractsDtosColumnItemDto>(createServerWorkflowsContractsDtosColumnItemDtoFromDiscriminatorValue); },
        "description": n => { serverWorkflowsContractsCommandsAddWorkflowCommand.description = n.getStringValue(); },
        "name": n => { serverWorkflowsContractsCommandsAddWorkflowCommand.name = n.getStringValue(); },
        "tenantId": n => { serverWorkflowsContractsCommandsAddWorkflowCommand.tenantId = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerWorkflowsContractsCommandsAssignWorkflowToUserCommand(serverWorkflowsContractsCommandsAssignWorkflowToUserCommand: Partial<ServerWorkflowsContractsCommandsAssignWorkflowToUserCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "userId": n => { serverWorkflowsContractsCommandsAssignWorkflowToUserCommand.userId = n.getStringValue(); },
        "workflowId": n => { serverWorkflowsContractsCommandsAssignWorkflowToUserCommand.workflowId = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerWorkflowsContractsCommandsEditWorkflowCommand(serverWorkflowsContractsCommandsEditWorkflowCommand: Partial<ServerWorkflowsContractsCommandsEditWorkflowCommand> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "columns": n => { serverWorkflowsContractsCommandsEditWorkflowCommand.columns = n.getCollectionOfObjectValues<ServerWorkflowsContractsDtosEditColumnItemDto>(createServerWorkflowsContractsDtosEditColumnItemDtoFromDiscriminatorValue); },
        "description": n => { serverWorkflowsContractsCommandsEditWorkflowCommand.description = n.getStringValue(); },
        "id": n => { serverWorkflowsContractsCommandsEditWorkflowCommand.id = n.getStringValue(); },
        "name": n => { serverWorkflowsContractsCommandsEditWorkflowCommand.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerWorkflowsContractsDtosAddWorkflowResponseDto(serverWorkflowsContractsDtosAddWorkflowResponseDto: Partial<ServerWorkflowsContractsDtosAddWorkflowResponseDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { serverWorkflowsContractsDtosAddWorkflowResponseDto.id = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerWorkflowsContractsDtosAllowedWorkflowDto(serverWorkflowsContractsDtosAllowedWorkflowDto: Partial<ServerWorkflowsContractsDtosAllowedWorkflowDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "description": n => { serverWorkflowsContractsDtosAllowedWorkflowDto.description = n.getStringValue(); },
        "id": n => { serverWorkflowsContractsDtosAllowedWorkflowDto.id = n.getStringValue(); },
        "name": n => { serverWorkflowsContractsDtosAllowedWorkflowDto.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerWorkflowsContractsDtosAssignWorkflowToUserResponseDto(serverWorkflowsContractsDtosAssignWorkflowToUserResponseDto: Partial<ServerWorkflowsContractsDtosAssignWorkflowToUserResponseDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "result": n => { serverWorkflowsContractsDtosAssignWorkflowToUserResponseDto.result = n.getBooleanValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerWorkflowsContractsDtosColumnItemDto(serverWorkflowsContractsDtosColumnItemDto: Partial<ServerWorkflowsContractsDtosColumnItemDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "description": n => { serverWorkflowsContractsDtosColumnItemDto.description = n.getStringValue(); },
        "id": n => { serverWorkflowsContractsDtosColumnItemDto.id = n.getStringValue(); },
        "positionIndex": n => { serverWorkflowsContractsDtosColumnItemDto.positionIndex = n.getNumberValue(); },
        "title": n => { serverWorkflowsContractsDtosColumnItemDto.title = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerWorkflowsContractsDtosColumnItemResponseDto(serverWorkflowsContractsDtosColumnItemResponseDto: Partial<ServerWorkflowsContractsDtosColumnItemResponseDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "description": n => { serverWorkflowsContractsDtosColumnItemResponseDto.description = n.getStringValue(); },
        "id": n => { serverWorkflowsContractsDtosColumnItemResponseDto.id = n.getStringValue(); },
        "positionIndex": n => { serverWorkflowsContractsDtosColumnItemResponseDto.positionIndex = n.getNumberValue(); },
        "title": n => { serverWorkflowsContractsDtosColumnItemResponseDto.title = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerWorkflowsContractsDtosEditColumnItemDto(serverWorkflowsContractsDtosEditColumnItemDto: Partial<ServerWorkflowsContractsDtosEditColumnItemDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "description": n => { serverWorkflowsContractsDtosEditColumnItemDto.description = n.getStringValue(); },
        "id": n => { serverWorkflowsContractsDtosEditColumnItemDto.id = n.getStringValue(); },
        "positionIndex": n => { serverWorkflowsContractsDtosEditColumnItemDto.positionIndex = n.getNumberValue(); },
        "title": n => { serverWorkflowsContractsDtosEditColumnItemDto.title = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerWorkflowsContractsDtosEditWorkflowResponseDto(serverWorkflowsContractsDtosEditWorkflowResponseDto: Partial<ServerWorkflowsContractsDtosEditWorkflowResponseDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "id": n => { serverWorkflowsContractsDtosEditWorkflowResponseDto.id = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerWorkflowsContractsDtosGetAllowedWorkflowsByUserResponseDto(serverWorkflowsContractsDtosGetAllowedWorkflowsByUserResponseDto: Partial<ServerWorkflowsContractsDtosGetAllowedWorkflowsByUserResponseDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "allowedWorkflows": n => { serverWorkflowsContractsDtosGetAllowedWorkflowsByUserResponseDto.allowedWorkflows = n.getCollectionOfObjectValues<ServerWorkflowsContractsDtosAllowedWorkflowDto>(createServerWorkflowsContractsDtosAllowedWorkflowDtoFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerWorkflowsContractsDtosGetKanbanCardsByColumnIdResponseDto(serverWorkflowsContractsDtosGetKanbanCardsByColumnIdResponseDto: Partial<ServerWorkflowsContractsDtosGetKanbanCardsByColumnIdResponseDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "kanbanCards": n => { serverWorkflowsContractsDtosGetKanbanCardsByColumnIdResponseDto.kanbanCards = n.getCollectionOfObjectValues<ServerWorkflowsContractsCardsKanbanCardDto>(createServerWorkflowsContractsCardsKanbanCardDtoFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerWorkflowsContractsDtosGetWorkflowByIdResponseDto(serverWorkflowsContractsDtosGetWorkflowByIdResponseDto: Partial<ServerWorkflowsContractsDtosGetWorkflowByIdResponseDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "columns": n => { serverWorkflowsContractsDtosGetWorkflowByIdResponseDto.columns = n.getCollectionOfObjectValues<ServerWorkflowsContractsDtosColumnItemResponseDto>(createServerWorkflowsContractsDtosColumnItemResponseDtoFromDiscriminatorValue); },
        "description": n => { serverWorkflowsContractsDtosGetWorkflowByIdResponseDto.description = n.getStringValue(); },
        "id": n => { serverWorkflowsContractsDtosGetWorkflowByIdResponseDto.id = n.getStringValue(); },
        "title": n => { serverWorkflowsContractsDtosGetWorkflowByIdResponseDto.title = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerWorkflowsContractsDtosGetWorkflowsResponseDto(serverWorkflowsContractsDtosGetWorkflowsResponseDto: Partial<ServerWorkflowsContractsDtosGetWorkflowsResponseDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "workflows": n => { serverWorkflowsContractsDtosGetWorkflowsResponseDto.workflows = n.getCollectionOfObjectValues<ServerWorkflowsContractsDtosWorkflowDto>(createServerWorkflowsContractsDtosWorkflowDtoFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerWorkflowsContractsDtosWorkflowColumnDto(serverWorkflowsContractsDtosWorkflowColumnDto: Partial<ServerWorkflowsContractsDtosWorkflowColumnDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "description": n => { serverWorkflowsContractsDtosWorkflowColumnDto.description = n.getStringValue(); },
        "id": n => { serverWorkflowsContractsDtosWorkflowColumnDto.id = n.getStringValue(); },
        "positionIndex": n => { serverWorkflowsContractsDtosWorkflowColumnDto.positionIndex = n.getNumberValue(); },
        "title": n => { serverWorkflowsContractsDtosWorkflowColumnDto.title = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoServerWorkflowsContractsDtosWorkflowDto(serverWorkflowsContractsDtosWorkflowDto: Partial<ServerWorkflowsContractsDtosWorkflowDto> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "columns": n => { serverWorkflowsContractsDtosWorkflowDto.columns = n.getCollectionOfObjectValues<ServerWorkflowsContractsDtosWorkflowColumnDto>(createServerWorkflowsContractsDtosWorkflowColumnDtoFromDiscriminatorValue); },
        "description": n => { serverWorkflowsContractsDtosWorkflowDto.description = n.getStringValue(); },
        "id": n => { serverWorkflowsContractsDtosWorkflowDto.id = n.getStringValue(); },
        "name": n => { serverWorkflowsContractsDtosWorkflowDto.name = n.getStringValue(); },
    }
}
/**
 * the dto used to send an error response to the client
 */
export interface FastEndpointsErrorResponse extends ApiError, Parsable {
    /**
     * the collection of errors for the current context
     */
    errors?: FastEndpointsErrorResponse_errors | null;
    /**
     * the message for the error response
     */
    messageEscaped?: string | null;
    /**
     * the http status code sent to the client. default is 400.
     */
    statusCode?: number | null;
}
/**
 * the collection of errors for the current context
 */
export interface FastEndpointsErrorResponse_errors extends AdditionalDataHolder, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFastEndpointsErrorResponse(writer: SerializationWriter, fastEndpointsErrorResponse: Partial<FastEndpointsErrorResponse> | undefined | null = {}) : void {
    if (fastEndpointsErrorResponse) {
        writer.writeObjectValue<FastEndpointsErrorResponse_errors>("errors", fastEndpointsErrorResponse.errors, serializeFastEndpointsErrorResponse_errors);
        writer.writeStringValue("message", fastEndpointsErrorResponse.messageEscaped ?? "One or more errors occurred!");
        writer.writeNumberValue("statusCode", fastEndpointsErrorResponse.statusCode);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFastEndpointsErrorResponse_errors(writer: SerializationWriter, fastEndpointsErrorResponse_errors: Partial<FastEndpointsErrorResponse_errors> | undefined | null = {}) : void {
    if (fastEndpointsErrorResponse_errors) {
        writer.writeAdditionalData(fastEndpointsErrorResponse_errors.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerNotificationContractsMessageDtosGetMessageResponseDto(writer: SerializationWriter, serverNotificationContractsMessageDtosGetMessageResponseDto: Partial<ServerNotificationContractsMessageDtosGetMessageResponseDto> | undefined | null = {}) : void {
    if (serverNotificationContractsMessageDtosGetMessageResponseDto) {
        writer.writeStringValue("text", serverNotificationContractsMessageDtosGetMessageResponseDto.text);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerNotificationContractsMessageQueriesGetMessageQuery(writer: SerializationWriter, serverNotificationContractsMessageQueriesGetMessageQuery: Partial<ServerNotificationContractsMessageQueriesGetMessageQuery> | undefined | null = {}) : void {
    if (serverNotificationContractsMessageQueriesGetMessageQuery) {
        writer.writeStringValue("text", serverNotificationContractsMessageQueriesGetMessageQuery.text);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerSharedModelsApiResponseOfAddHubResponse(writer: SerializationWriter, serverSharedModelsApiResponseOfAddHubResponse: Partial<ServerSharedModelsApiResponseOfAddHubResponse> | undefined | null = {}) : void {
    if (serverSharedModelsApiResponseOfAddHubResponse) {
        writer.writeObjectValue<ServerSocialNetworkContractsHubsAddHubResponse>("data", serverSharedModelsApiResponseOfAddHubResponse.data, serializeServerSocialNetworkContractsHubsAddHubResponse);
        writer.writeCollectionOfPrimitiveValues<string>("errors", serverSharedModelsApiResponseOfAddHubResponse.errors);
        writer.writeBooleanValue("isSuccess", serverSharedModelsApiResponseOfAddHubResponse.isSuccess);
        writer.writeStringValue("message", serverSharedModelsApiResponseOfAddHubResponse.message);
        writer.writeCollectionOfPrimitiveValues<string>("validationErrors", serverSharedModelsApiResponseOfAddHubResponse.validationErrors);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerSharedModelsApiResponseOfAddWorkflowResponseDto(writer: SerializationWriter, serverSharedModelsApiResponseOfAddWorkflowResponseDto: Partial<ServerSharedModelsApiResponseOfAddWorkflowResponseDto> | undefined | null = {}) : void {
    if (serverSharedModelsApiResponseOfAddWorkflowResponseDto) {
        writer.writeObjectValue<ServerWorkflowsContractsDtosAddWorkflowResponseDto>("data", serverSharedModelsApiResponseOfAddWorkflowResponseDto.data, serializeServerWorkflowsContractsDtosAddWorkflowResponseDto);
        writer.writeCollectionOfPrimitiveValues<string>("errors", serverSharedModelsApiResponseOfAddWorkflowResponseDto.errors);
        writer.writeBooleanValue("isSuccess", serverSharedModelsApiResponseOfAddWorkflowResponseDto.isSuccess);
        writer.writeStringValue("message", serverSharedModelsApiResponseOfAddWorkflowResponseDto.message);
        writer.writeCollectionOfPrimitiveValues<string>("validationErrors", serverSharedModelsApiResponseOfAddWorkflowResponseDto.validationErrors);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerSharedModelsApiResponseOfAssignWorkflowToUserResponseDto(writer: SerializationWriter, serverSharedModelsApiResponseOfAssignWorkflowToUserResponseDto: Partial<ServerSharedModelsApiResponseOfAssignWorkflowToUserResponseDto> | undefined | null = {}) : void {
    if (serverSharedModelsApiResponseOfAssignWorkflowToUserResponseDto) {
        writer.writeObjectValue<ServerWorkflowsContractsDtosAssignWorkflowToUserResponseDto>("data", serverSharedModelsApiResponseOfAssignWorkflowToUserResponseDto.data, serializeServerWorkflowsContractsDtosAssignWorkflowToUserResponseDto);
        writer.writeCollectionOfPrimitiveValues<string>("errors", serverSharedModelsApiResponseOfAssignWorkflowToUserResponseDto.errors);
        writer.writeBooleanValue("isSuccess", serverSharedModelsApiResponseOfAssignWorkflowToUserResponseDto.isSuccess);
        writer.writeStringValue("message", serverSharedModelsApiResponseOfAssignWorkflowToUserResponseDto.message);
        writer.writeCollectionOfPrimitiveValues<string>("validationErrors", serverSharedModelsApiResponseOfAssignWorkflowToUserResponseDto.validationErrors);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerSharedModelsApiResponseOfEditWorkflowResponseDto(writer: SerializationWriter, serverSharedModelsApiResponseOfEditWorkflowResponseDto: Partial<ServerSharedModelsApiResponseOfEditWorkflowResponseDto> | undefined | null = {}) : void {
    if (serverSharedModelsApiResponseOfEditWorkflowResponseDto) {
        writer.writeObjectValue<ServerWorkflowsContractsDtosEditWorkflowResponseDto>("data", serverSharedModelsApiResponseOfEditWorkflowResponseDto.data, serializeServerWorkflowsContractsDtosEditWorkflowResponseDto);
        writer.writeCollectionOfPrimitiveValues<string>("errors", serverSharedModelsApiResponseOfEditWorkflowResponseDto.errors);
        writer.writeBooleanValue("isSuccess", serverSharedModelsApiResponseOfEditWorkflowResponseDto.isSuccess);
        writer.writeStringValue("message", serverSharedModelsApiResponseOfEditWorkflowResponseDto.message);
        writer.writeCollectionOfPrimitiveValues<string>("validationErrors", serverSharedModelsApiResponseOfEditWorkflowResponseDto.validationErrors);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerSharedModelsApiResponseOfGetAllowedWorkflowsByUserResponseDto(writer: SerializationWriter, serverSharedModelsApiResponseOfGetAllowedWorkflowsByUserResponseDto: Partial<ServerSharedModelsApiResponseOfGetAllowedWorkflowsByUserResponseDto> | undefined | null = {}) : void {
    if (serverSharedModelsApiResponseOfGetAllowedWorkflowsByUserResponseDto) {
        writer.writeObjectValue<ServerWorkflowsContractsDtosGetAllowedWorkflowsByUserResponseDto>("data", serverSharedModelsApiResponseOfGetAllowedWorkflowsByUserResponseDto.data, serializeServerWorkflowsContractsDtosGetAllowedWorkflowsByUserResponseDto);
        writer.writeCollectionOfPrimitiveValues<string>("errors", serverSharedModelsApiResponseOfGetAllowedWorkflowsByUserResponseDto.errors);
        writer.writeBooleanValue("isSuccess", serverSharedModelsApiResponseOfGetAllowedWorkflowsByUserResponseDto.isSuccess);
        writer.writeStringValue("message", serverSharedModelsApiResponseOfGetAllowedWorkflowsByUserResponseDto.message);
        writer.writeCollectionOfPrimitiveValues<string>("validationErrors", serverSharedModelsApiResponseOfGetAllowedWorkflowsByUserResponseDto.validationErrors);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerSharedModelsApiResponseOfGetHubsResponse(writer: SerializationWriter, serverSharedModelsApiResponseOfGetHubsResponse: Partial<ServerSharedModelsApiResponseOfGetHubsResponse> | undefined | null = {}) : void {
    if (serverSharedModelsApiResponseOfGetHubsResponse) {
        writer.writeObjectValue<ServerSocialNetworkContractsHubsGetHubsResponse>("data", serverSharedModelsApiResponseOfGetHubsResponse.data, serializeServerSocialNetworkContractsHubsGetHubsResponse);
        writer.writeCollectionOfPrimitiveValues<string>("errors", serverSharedModelsApiResponseOfGetHubsResponse.errors);
        writer.writeBooleanValue("isSuccess", serverSharedModelsApiResponseOfGetHubsResponse.isSuccess);
        writer.writeStringValue("message", serverSharedModelsApiResponseOfGetHubsResponse.message);
        writer.writeCollectionOfPrimitiveValues<string>("validationErrors", serverSharedModelsApiResponseOfGetHubsResponse.validationErrors);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerSharedModelsApiResponseOfGetKanbanCardsByColumnIdResponseDto(writer: SerializationWriter, serverSharedModelsApiResponseOfGetKanbanCardsByColumnIdResponseDto: Partial<ServerSharedModelsApiResponseOfGetKanbanCardsByColumnIdResponseDto> | undefined | null = {}) : void {
    if (serverSharedModelsApiResponseOfGetKanbanCardsByColumnIdResponseDto) {
        writer.writeObjectValue<ServerWorkflowsContractsDtosGetKanbanCardsByColumnIdResponseDto>("data", serverSharedModelsApiResponseOfGetKanbanCardsByColumnIdResponseDto.data, serializeServerWorkflowsContractsDtosGetKanbanCardsByColumnIdResponseDto);
        writer.writeCollectionOfPrimitiveValues<string>("errors", serverSharedModelsApiResponseOfGetKanbanCardsByColumnIdResponseDto.errors);
        writer.writeBooleanValue("isSuccess", serverSharedModelsApiResponseOfGetKanbanCardsByColumnIdResponseDto.isSuccess);
        writer.writeStringValue("message", serverSharedModelsApiResponseOfGetKanbanCardsByColumnIdResponseDto.message);
        writer.writeCollectionOfPrimitiveValues<string>("validationErrors", serverSharedModelsApiResponseOfGetKanbanCardsByColumnIdResponseDto.validationErrors);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerSharedModelsApiResponseOfGetWorkflowByIdResponseDto(writer: SerializationWriter, serverSharedModelsApiResponseOfGetWorkflowByIdResponseDto: Partial<ServerSharedModelsApiResponseOfGetWorkflowByIdResponseDto> | undefined | null = {}) : void {
    if (serverSharedModelsApiResponseOfGetWorkflowByIdResponseDto) {
        writer.writeObjectValue<ServerWorkflowsContractsDtosGetWorkflowByIdResponseDto>("data", serverSharedModelsApiResponseOfGetWorkflowByIdResponseDto.data, serializeServerWorkflowsContractsDtosGetWorkflowByIdResponseDto);
        writer.writeCollectionOfPrimitiveValues<string>("errors", serverSharedModelsApiResponseOfGetWorkflowByIdResponseDto.errors);
        writer.writeBooleanValue("isSuccess", serverSharedModelsApiResponseOfGetWorkflowByIdResponseDto.isSuccess);
        writer.writeStringValue("message", serverSharedModelsApiResponseOfGetWorkflowByIdResponseDto.message);
        writer.writeCollectionOfPrimitiveValues<string>("validationErrors", serverSharedModelsApiResponseOfGetWorkflowByIdResponseDto.validationErrors);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerSharedModelsApiResponseOfGetWorkflowsResponseDto(writer: SerializationWriter, serverSharedModelsApiResponseOfGetWorkflowsResponseDto: Partial<ServerSharedModelsApiResponseOfGetWorkflowsResponseDto> | undefined | null = {}) : void {
    if (serverSharedModelsApiResponseOfGetWorkflowsResponseDto) {
        writer.writeObjectValue<ServerWorkflowsContractsDtosGetWorkflowsResponseDto>("data", serverSharedModelsApiResponseOfGetWorkflowsResponseDto.data, serializeServerWorkflowsContractsDtosGetWorkflowsResponseDto);
        writer.writeCollectionOfPrimitiveValues<string>("errors", serverSharedModelsApiResponseOfGetWorkflowsResponseDto.errors);
        writer.writeBooleanValue("isSuccess", serverSharedModelsApiResponseOfGetWorkflowsResponseDto.isSuccess);
        writer.writeStringValue("message", serverSharedModelsApiResponseOfGetWorkflowsResponseDto.message);
        writer.writeCollectionOfPrimitiveValues<string>("validationErrors", serverSharedModelsApiResponseOfGetWorkflowsResponseDto.validationErrors);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerSocialNetworkContractsHubsAddHubResponse(writer: SerializationWriter, serverSocialNetworkContractsHubsAddHubResponse: Partial<ServerSocialNetworkContractsHubsAddHubResponse> | undefined | null = {}) : void {
    if (serverSocialNetworkContractsHubsAddHubResponse) {
        writer.writeStringValue("id", serverSocialNetworkContractsHubsAddHubResponse.id);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerSocialNetworkContractsHubsGetHubsResponse(writer: SerializationWriter, serverSocialNetworkContractsHubsGetHubsResponse: Partial<ServerSocialNetworkContractsHubsGetHubsResponse> | undefined | null = {}) : void {
    if (serverSocialNetworkContractsHubsGetHubsResponse) {
        writer.writeCollectionOfObjectValues<ServerSocialNetworkContractsHubsHubItem>("items", serverSocialNetworkContractsHubsGetHubsResponse.items, serializeServerSocialNetworkContractsHubsHubItem);
        writer.writeStringValue("tenantId", serverSocialNetworkContractsHubsGetHubsResponse.tenantId);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerSocialNetworkContractsHubsHubItem(writer: SerializationWriter, serverSocialNetworkContractsHubsHubItem: Partial<ServerSocialNetworkContractsHubsHubItem> | undefined | null = {}) : void {
    if (serverSocialNetworkContractsHubsHubItem) {
        writer.writeStringValue("hubId", serverSocialNetworkContractsHubsHubItem.hubId);
        writer.writeStringValue("phoneNumber", serverSocialNetworkContractsHubsHubItem.phoneNumber);
        writer.writeStringValue("platformId", serverSocialNetworkContractsHubsHubItem.platformId);
        writer.writeStringValue("status", serverSocialNetworkContractsHubsHubItem.status);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerSocialNetworkEndPointsHubsRequestsAddHubRequest(writer: SerializationWriter, serverSocialNetworkEndPointsHubsRequestsAddHubRequest: Partial<ServerSocialNetworkEndPointsHubsRequestsAddHubRequest> | undefined | null = {}) : void {
    if (serverSocialNetworkEndPointsHubsRequestsAddHubRequest) {
        writer.writeStringValue("name", serverSocialNetworkEndPointsHubsRequestsAddHubRequest.name);
        writer.writeStringValue("phoneNumber", serverSocialNetworkEndPointsHubsRequestsAddHubRequest.phoneNumber);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerSocialNetworkSimulatorEndPointsWebHoooksMessageRequest(writer: SerializationWriter, serverSocialNetworkSimulatorEndPointsWebHoooksMessageRequest: Partial<ServerSocialNetworkSimulatorEndPointsWebHoooksMessageRequest> | undefined | null = {}) : void {
    if (serverSocialNetworkSimulatorEndPointsWebHoooksMessageRequest) {
        writer.writeStringValue("message", serverSocialNetworkSimulatorEndPointsWebHoooksMessageRequest.message);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerSocialNetworkSimulatorEndPointsWebHoooksMessageResponse(writer: SerializationWriter, serverSocialNetworkSimulatorEndPointsWebHoooksMessageResponse: Partial<ServerSocialNetworkSimulatorEndPointsWebHoooksMessageResponse> | undefined | null = {}) : void {
    if (serverSocialNetworkSimulatorEndPointsWebHoooksMessageResponse) {
        writer.writeStringValue("status", serverSocialNetworkSimulatorEndPointsWebHoooksMessageResponse.status);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerWorkflowsContractsCardsCardContentTypesICardContentType(writer: SerializationWriter, serverWorkflowsContractsCardsCardContentTypesICardContentType: Partial<ServerWorkflowsContractsCardsCardContentTypesICardContentType> | undefined | null = {}) : void {
    if (serverWorkflowsContractsCardsCardContentTypesICardContentType) {
        writer.writeStringValue("contentType", serverWorkflowsContractsCardsCardContentTypesICardContentType.contentType);
        writer.writeStringValue("hubId", serverWorkflowsContractsCardsCardContentTypesICardContentType.hubId);
        writer.writeStringValue("platformId", serverWorkflowsContractsCardsCardContentTypesICardContentType.platformId);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerWorkflowsContractsCardsKanbanCardDto(writer: SerializationWriter, serverWorkflowsContractsCardsKanbanCardDto: Partial<ServerWorkflowsContractsCardsKanbanCardDto> | undefined | null = {}) : void {
    if (serverWorkflowsContractsCardsKanbanCardDto) {
        writer.writeStringValue("columnId", serverWorkflowsContractsCardsKanbanCardDto.columnId);
        writer.writeObjectValue<ServerWorkflowsContractsCardsCardContentTypesICardContentType>("content", serverWorkflowsContractsCardsKanbanCardDto.content, serializeServerWorkflowsContractsCardsCardContentTypesICardContentType);
        writer.writeStringValue("id", serverWorkflowsContractsCardsKanbanCardDto.id);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerWorkflowsContractsCommandsAddWorkflowCommand(writer: SerializationWriter, serverWorkflowsContractsCommandsAddWorkflowCommand: Partial<ServerWorkflowsContractsCommandsAddWorkflowCommand> | undefined | null = {}) : void {
    if (serverWorkflowsContractsCommandsAddWorkflowCommand) {
        writer.writeCollectionOfObjectValues<ServerWorkflowsContractsDtosColumnItemDto>("columns", serverWorkflowsContractsCommandsAddWorkflowCommand.columns, serializeServerWorkflowsContractsDtosColumnItemDto);
        writer.writeStringValue("description", serverWorkflowsContractsCommandsAddWorkflowCommand.description);
        writer.writeStringValue("name", serverWorkflowsContractsCommandsAddWorkflowCommand.name);
        writer.writeStringValue("tenantId", serverWorkflowsContractsCommandsAddWorkflowCommand.tenantId);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerWorkflowsContractsCommandsAssignWorkflowToUserCommand(writer: SerializationWriter, serverWorkflowsContractsCommandsAssignWorkflowToUserCommand: Partial<ServerWorkflowsContractsCommandsAssignWorkflowToUserCommand> | undefined | null = {}) : void {
    if (serverWorkflowsContractsCommandsAssignWorkflowToUserCommand) {
        writer.writeStringValue("userId", serverWorkflowsContractsCommandsAssignWorkflowToUserCommand.userId);
        writer.writeStringValue("workflowId", serverWorkflowsContractsCommandsAssignWorkflowToUserCommand.workflowId);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerWorkflowsContractsCommandsEditWorkflowCommand(writer: SerializationWriter, serverWorkflowsContractsCommandsEditWorkflowCommand: Partial<ServerWorkflowsContractsCommandsEditWorkflowCommand> | undefined | null = {}) : void {
    if (serverWorkflowsContractsCommandsEditWorkflowCommand) {
        writer.writeCollectionOfObjectValues<ServerWorkflowsContractsDtosEditColumnItemDto>("columns", serverWorkflowsContractsCommandsEditWorkflowCommand.columns, serializeServerWorkflowsContractsDtosEditColumnItemDto);
        writer.writeStringValue("description", serverWorkflowsContractsCommandsEditWorkflowCommand.description);
        writer.writeStringValue("id", serverWorkflowsContractsCommandsEditWorkflowCommand.id);
        writer.writeStringValue("name", serverWorkflowsContractsCommandsEditWorkflowCommand.name);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerWorkflowsContractsDtosAddWorkflowResponseDto(writer: SerializationWriter, serverWorkflowsContractsDtosAddWorkflowResponseDto: Partial<ServerWorkflowsContractsDtosAddWorkflowResponseDto> | undefined | null = {}) : void {
    if (serverWorkflowsContractsDtosAddWorkflowResponseDto) {
        writer.writeStringValue("id", serverWorkflowsContractsDtosAddWorkflowResponseDto.id);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerWorkflowsContractsDtosAllowedWorkflowDto(writer: SerializationWriter, serverWorkflowsContractsDtosAllowedWorkflowDto: Partial<ServerWorkflowsContractsDtosAllowedWorkflowDto> | undefined | null = {}) : void {
    if (serverWorkflowsContractsDtosAllowedWorkflowDto) {
        writer.writeStringValue("description", serverWorkflowsContractsDtosAllowedWorkflowDto.description);
        writer.writeStringValue("id", serverWorkflowsContractsDtosAllowedWorkflowDto.id);
        writer.writeStringValue("name", serverWorkflowsContractsDtosAllowedWorkflowDto.name);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerWorkflowsContractsDtosAssignWorkflowToUserResponseDto(writer: SerializationWriter, serverWorkflowsContractsDtosAssignWorkflowToUserResponseDto: Partial<ServerWorkflowsContractsDtosAssignWorkflowToUserResponseDto> | undefined | null = {}) : void {
    if (serverWorkflowsContractsDtosAssignWorkflowToUserResponseDto) {
        writer.writeBooleanValue("result", serverWorkflowsContractsDtosAssignWorkflowToUserResponseDto.result);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerWorkflowsContractsDtosColumnItemDto(writer: SerializationWriter, serverWorkflowsContractsDtosColumnItemDto: Partial<ServerWorkflowsContractsDtosColumnItemDto> | undefined | null = {}) : void {
    if (serverWorkflowsContractsDtosColumnItemDto) {
        writer.writeStringValue("description", serverWorkflowsContractsDtosColumnItemDto.description);
        writer.writeStringValue("id", serverWorkflowsContractsDtosColumnItemDto.id);
        writer.writeNumberValue("positionIndex", serverWorkflowsContractsDtosColumnItemDto.positionIndex);
        writer.writeStringValue("title", serverWorkflowsContractsDtosColumnItemDto.title);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerWorkflowsContractsDtosColumnItemResponseDto(writer: SerializationWriter, serverWorkflowsContractsDtosColumnItemResponseDto: Partial<ServerWorkflowsContractsDtosColumnItemResponseDto> | undefined | null = {}) : void {
    if (serverWorkflowsContractsDtosColumnItemResponseDto) {
        writer.writeStringValue("description", serverWorkflowsContractsDtosColumnItemResponseDto.description);
        writer.writeStringValue("id", serverWorkflowsContractsDtosColumnItemResponseDto.id);
        writer.writeNumberValue("positionIndex", serverWorkflowsContractsDtosColumnItemResponseDto.positionIndex);
        writer.writeStringValue("title", serverWorkflowsContractsDtosColumnItemResponseDto.title);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerWorkflowsContractsDtosEditColumnItemDto(writer: SerializationWriter, serverWorkflowsContractsDtosEditColumnItemDto: Partial<ServerWorkflowsContractsDtosEditColumnItemDto> | undefined | null = {}) : void {
    if (serverWorkflowsContractsDtosEditColumnItemDto) {
        writer.writeStringValue("description", serverWorkflowsContractsDtosEditColumnItemDto.description);
        writer.writeStringValue("id", serverWorkflowsContractsDtosEditColumnItemDto.id);
        writer.writeNumberValue("positionIndex", serverWorkflowsContractsDtosEditColumnItemDto.positionIndex);
        writer.writeStringValue("title", serverWorkflowsContractsDtosEditColumnItemDto.title);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerWorkflowsContractsDtosEditWorkflowResponseDto(writer: SerializationWriter, serverWorkflowsContractsDtosEditWorkflowResponseDto: Partial<ServerWorkflowsContractsDtosEditWorkflowResponseDto> | undefined | null = {}) : void {
    if (serverWorkflowsContractsDtosEditWorkflowResponseDto) {
        writer.writeStringValue("id", serverWorkflowsContractsDtosEditWorkflowResponseDto.id);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerWorkflowsContractsDtosGetAllowedWorkflowsByUserResponseDto(writer: SerializationWriter, serverWorkflowsContractsDtosGetAllowedWorkflowsByUserResponseDto: Partial<ServerWorkflowsContractsDtosGetAllowedWorkflowsByUserResponseDto> | undefined | null = {}) : void {
    if (serverWorkflowsContractsDtosGetAllowedWorkflowsByUserResponseDto) {
        writer.writeCollectionOfObjectValues<ServerWorkflowsContractsDtosAllowedWorkflowDto>("allowedWorkflows", serverWorkflowsContractsDtosGetAllowedWorkflowsByUserResponseDto.allowedWorkflows, serializeServerWorkflowsContractsDtosAllowedWorkflowDto);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerWorkflowsContractsDtosGetKanbanCardsByColumnIdResponseDto(writer: SerializationWriter, serverWorkflowsContractsDtosGetKanbanCardsByColumnIdResponseDto: Partial<ServerWorkflowsContractsDtosGetKanbanCardsByColumnIdResponseDto> | undefined | null = {}) : void {
    if (serverWorkflowsContractsDtosGetKanbanCardsByColumnIdResponseDto) {
        writer.writeCollectionOfObjectValues<ServerWorkflowsContractsCardsKanbanCardDto>("kanbanCards", serverWorkflowsContractsDtosGetKanbanCardsByColumnIdResponseDto.kanbanCards, serializeServerWorkflowsContractsCardsKanbanCardDto);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerWorkflowsContractsDtosGetWorkflowByIdResponseDto(writer: SerializationWriter, serverWorkflowsContractsDtosGetWorkflowByIdResponseDto: Partial<ServerWorkflowsContractsDtosGetWorkflowByIdResponseDto> | undefined | null = {}) : void {
    if (serverWorkflowsContractsDtosGetWorkflowByIdResponseDto) {
        writer.writeCollectionOfObjectValues<ServerWorkflowsContractsDtosColumnItemResponseDto>("columns", serverWorkflowsContractsDtosGetWorkflowByIdResponseDto.columns, serializeServerWorkflowsContractsDtosColumnItemResponseDto);
        writer.writeStringValue("description", serverWorkflowsContractsDtosGetWorkflowByIdResponseDto.description);
        writer.writeStringValue("id", serverWorkflowsContractsDtosGetWorkflowByIdResponseDto.id);
        writer.writeStringValue("title", serverWorkflowsContractsDtosGetWorkflowByIdResponseDto.title);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerWorkflowsContractsDtosGetWorkflowsResponseDto(writer: SerializationWriter, serverWorkflowsContractsDtosGetWorkflowsResponseDto: Partial<ServerWorkflowsContractsDtosGetWorkflowsResponseDto> | undefined | null = {}) : void {
    if (serverWorkflowsContractsDtosGetWorkflowsResponseDto) {
        writer.writeCollectionOfObjectValues<ServerWorkflowsContractsDtosWorkflowDto>("workflows", serverWorkflowsContractsDtosGetWorkflowsResponseDto.workflows, serializeServerWorkflowsContractsDtosWorkflowDto);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerWorkflowsContractsDtosWorkflowColumnDto(writer: SerializationWriter, serverWorkflowsContractsDtosWorkflowColumnDto: Partial<ServerWorkflowsContractsDtosWorkflowColumnDto> | undefined | null = {}) : void {
    if (serverWorkflowsContractsDtosWorkflowColumnDto) {
        writer.writeStringValue("description", serverWorkflowsContractsDtosWorkflowColumnDto.description);
        writer.writeStringValue("id", serverWorkflowsContractsDtosWorkflowColumnDto.id);
        writer.writeNumberValue("positionIndex", serverWorkflowsContractsDtosWorkflowColumnDto.positionIndex);
        writer.writeStringValue("title", serverWorkflowsContractsDtosWorkflowColumnDto.title);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeServerWorkflowsContractsDtosWorkflowDto(writer: SerializationWriter, serverWorkflowsContractsDtosWorkflowDto: Partial<ServerWorkflowsContractsDtosWorkflowDto> | undefined | null = {}) : void {
    if (serverWorkflowsContractsDtosWorkflowDto) {
        writer.writeCollectionOfObjectValues<ServerWorkflowsContractsDtosWorkflowColumnDto>("columns", serverWorkflowsContractsDtosWorkflowDto.columns, serializeServerWorkflowsContractsDtosWorkflowColumnDto);
        writer.writeStringValue("description", serverWorkflowsContractsDtosWorkflowDto.description);
        writer.writeStringValue("id", serverWorkflowsContractsDtosWorkflowDto.id);
        writer.writeStringValue("name", serverWorkflowsContractsDtosWorkflowDto.name);
    }
}
export interface ServerNotificationContractsMessageDtosGetMessageResponseDto extends Parsable {
    /**
     * The text property
     */
    text?: string | null;
}
export interface ServerNotificationContractsMessageQueriesGetMessageQuery extends Parsable {
    /**
     * The text property
     */
    text?: string | null;
}
export interface ServerSharedModelsApiResponseOfAddHubResponse extends Parsable {
    /**
     * The data property
     */
    data?: ServerSocialNetworkContractsHubsAddHubResponse | null;
    /**
     * The errors property
     */
    errors?: string[] | null;
    /**
     * The isSuccess property
     */
    isSuccess?: boolean | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The validationErrors property
     */
    validationErrors?: string[] | null;
}
export interface ServerSharedModelsApiResponseOfAddWorkflowResponseDto extends Parsable {
    /**
     * The data property
     */
    data?: ServerWorkflowsContractsDtosAddWorkflowResponseDto | null;
    /**
     * The errors property
     */
    errors?: string[] | null;
    /**
     * The isSuccess property
     */
    isSuccess?: boolean | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The validationErrors property
     */
    validationErrors?: string[] | null;
}
export interface ServerSharedModelsApiResponseOfAssignWorkflowToUserResponseDto extends Parsable {
    /**
     * The data property
     */
    data?: ServerWorkflowsContractsDtosAssignWorkflowToUserResponseDto | null;
    /**
     * The errors property
     */
    errors?: string[] | null;
    /**
     * The isSuccess property
     */
    isSuccess?: boolean | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The validationErrors property
     */
    validationErrors?: string[] | null;
}
export interface ServerSharedModelsApiResponseOfEditWorkflowResponseDto extends Parsable {
    /**
     * The data property
     */
    data?: ServerWorkflowsContractsDtosEditWorkflowResponseDto | null;
    /**
     * The errors property
     */
    errors?: string[] | null;
    /**
     * The isSuccess property
     */
    isSuccess?: boolean | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The validationErrors property
     */
    validationErrors?: string[] | null;
}
export interface ServerSharedModelsApiResponseOfGetAllowedWorkflowsByUserResponseDto extends Parsable {
    /**
     * The data property
     */
    data?: ServerWorkflowsContractsDtosGetAllowedWorkflowsByUserResponseDto | null;
    /**
     * The errors property
     */
    errors?: string[] | null;
    /**
     * The isSuccess property
     */
    isSuccess?: boolean | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The validationErrors property
     */
    validationErrors?: string[] | null;
}
export interface ServerSharedModelsApiResponseOfGetHubsResponse extends Parsable {
    /**
     * The data property
     */
    data?: ServerSocialNetworkContractsHubsGetHubsResponse | null;
    /**
     * The errors property
     */
    errors?: string[] | null;
    /**
     * The isSuccess property
     */
    isSuccess?: boolean | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The validationErrors property
     */
    validationErrors?: string[] | null;
}
export interface ServerSharedModelsApiResponseOfGetKanbanCardsByColumnIdResponseDto extends Parsable {
    /**
     * The data property
     */
    data?: ServerWorkflowsContractsDtosGetKanbanCardsByColumnIdResponseDto | null;
    /**
     * The errors property
     */
    errors?: string[] | null;
    /**
     * The isSuccess property
     */
    isSuccess?: boolean | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The validationErrors property
     */
    validationErrors?: string[] | null;
}
export interface ServerSharedModelsApiResponseOfGetWorkflowByIdResponseDto extends Parsable {
    /**
     * The data property
     */
    data?: ServerWorkflowsContractsDtosGetWorkflowByIdResponseDto | null;
    /**
     * The errors property
     */
    errors?: string[] | null;
    /**
     * The isSuccess property
     */
    isSuccess?: boolean | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The validationErrors property
     */
    validationErrors?: string[] | null;
}
export interface ServerSharedModelsApiResponseOfGetWorkflowsResponseDto extends Parsable {
    /**
     * The data property
     */
    data?: ServerWorkflowsContractsDtosGetWorkflowsResponseDto | null;
    /**
     * The errors property
     */
    errors?: string[] | null;
    /**
     * The isSuccess property
     */
    isSuccess?: boolean | null;
    /**
     * The message property
     */
    message?: string | null;
    /**
     * The validationErrors property
     */
    validationErrors?: string[] | null;
}
export interface ServerSocialNetworkContractsHubsAddHubResponse extends Parsable {
    /**
     * The id property
     */
    id?: string | null;
}
export interface ServerSocialNetworkContractsHubsGetHubsResponse extends Parsable {
    /**
     * The items property
     */
    items?: ServerSocialNetworkContractsHubsHubItem[] | null;
    /**
     * The tenantId property
     */
    tenantId?: string | null;
}
export interface ServerSocialNetworkContractsHubsHubItem extends Parsable {
    /**
     * The hubId property
     */
    hubId?: string | null;
    /**
     * The phoneNumber property
     */
    phoneNumber?: string | null;
    /**
     * The platformId property
     */
    platformId?: string | null;
    /**
     * The status property
     */
    status?: string | null;
}
export interface ServerSocialNetworkEndPointsHubsRequestsAddHubRequest extends Parsable {
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The phoneNumber property
     */
    phoneNumber?: string | null;
}
export interface ServerSocialNetworkSimulatorEndPointsWebHoooksMessageRequest extends Parsable {
    /**
     * The message property
     */
    message?: string | null;
}
export interface ServerSocialNetworkSimulatorEndPointsWebHoooksMessageResponse extends Parsable {
    /**
     * The status property
     */
    status?: string | null;
}
export interface ServerWorkflowsContractsCardsCardContentTypesICardContentType extends Parsable {
    /**
     * The contentType property
     */
    contentType?: string | null;
    /**
     * The hubId property
     */
    hubId?: string | null;
    /**
     * The platformId property
     */
    platformId?: string | null;
}
export interface ServerWorkflowsContractsCardsKanbanCardDto extends Parsable {
    /**
     * The columnId property
     */
    columnId?: string | null;
    /**
     * The content property
     */
    content?: ServerWorkflowsContractsCardsCardContentTypesICardContentType | null;
    /**
     * The id property
     */
    id?: string | null;
}
export interface ServerWorkflowsContractsCommandsAddWorkflowCommand extends Parsable {
    /**
     * The columns property
     */
    columns?: ServerWorkflowsContractsDtosColumnItemDto[] | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The tenantId property
     */
    tenantId?: string | null;
}
export interface ServerWorkflowsContractsCommandsAssignWorkflowToUserCommand extends Parsable {
    /**
     * The userId property
     */
    userId?: string | null;
    /**
     * The workflowId property
     */
    workflowId?: string | null;
}
export interface ServerWorkflowsContractsCommandsEditWorkflowCommand extends Parsable {
    /**
     * The columns property
     */
    columns?: ServerWorkflowsContractsDtosEditColumnItemDto[] | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface ServerWorkflowsContractsDtosAddWorkflowResponseDto extends Parsable {
    /**
     * The id property
     */
    id?: string | null;
}
export interface ServerWorkflowsContractsDtosAllowedWorkflowDto extends Parsable {
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface ServerWorkflowsContractsDtosAssignWorkflowToUserResponseDto extends Parsable {
    /**
     * The result property
     */
    result?: boolean | null;
}
export interface ServerWorkflowsContractsDtosColumnItemDto extends Parsable {
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The positionIndex property
     */
    positionIndex?: number | null;
    /**
     * The title property
     */
    title?: string | null;
}
export interface ServerWorkflowsContractsDtosColumnItemResponseDto extends Parsable {
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The positionIndex property
     */
    positionIndex?: number | null;
    /**
     * The title property
     */
    title?: string | null;
}
export interface ServerWorkflowsContractsDtosEditColumnItemDto extends Parsable {
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The positionIndex property
     */
    positionIndex?: number | null;
    /**
     * The title property
     */
    title?: string | null;
}
export interface ServerWorkflowsContractsDtosEditWorkflowResponseDto extends Parsable {
    /**
     * The id property
     */
    id?: string | null;
}
export interface ServerWorkflowsContractsDtosGetAllowedWorkflowsByUserResponseDto extends Parsable {
    /**
     * The allowedWorkflows property
     */
    allowedWorkflows?: ServerWorkflowsContractsDtosAllowedWorkflowDto[] | null;
}
export interface ServerWorkflowsContractsDtosGetKanbanCardsByColumnIdResponseDto extends Parsable {
    /**
     * The kanbanCards property
     */
    kanbanCards?: ServerWorkflowsContractsCardsKanbanCardDto[] | null;
}
export interface ServerWorkflowsContractsDtosGetWorkflowByIdResponseDto extends Parsable {
    /**
     * The columns property
     */
    columns?: ServerWorkflowsContractsDtosColumnItemResponseDto[] | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The title property
     */
    title?: string | null;
}
export interface ServerWorkflowsContractsDtosGetWorkflowsResponseDto extends Parsable {
    /**
     * The workflows property
     */
    workflows?: ServerWorkflowsContractsDtosWorkflowDto[] | null;
}
export interface ServerWorkflowsContractsDtosWorkflowColumnDto extends Parsable {
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The positionIndex property
     */
    positionIndex?: number | null;
    /**
     * The title property
     */
    title?: string | null;
}
export interface ServerWorkflowsContractsDtosWorkflowDto extends Parsable {
    /**
     * The columns property
     */
    columns?: ServerWorkflowsContractsDtosWorkflowColumnDto[] | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
/* tslint:enable */
/* eslint-enable */
