/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFastEndpointsErrorResponseFromDiscriminatorValue, createServerSharedModelsApiResponseOfGetAllowedWorkflowsByUserResponseDtoFromDiscriminatorValue, type FastEndpointsErrorResponse, type ServerSharedModelsApiResponseOfGetAllowedWorkflowsByUserResponseDto } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /workflow/allowed-workflows
 */
export interface AllowedWorkflowsRequestBuilder extends BaseRequestBuilder<AllowedWorkflowsRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ServerSharedModelsApiResponseOfGetAllowedWorkflowsByUserResponseDto>}
     * @throws {FastEndpointsErrorResponse} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ServerSharedModelsApiResponseOfGetAllowedWorkflowsByUserResponseDto | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const AllowedWorkflowsRequestBuilderUriTemplate = "{+baseurl}/workflow/allowed-workflows";
/**
 * Metadata for all the requests in the request builder.
 */
export const AllowedWorkflowsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: AllowedWorkflowsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createFastEndpointsErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createServerSharedModelsApiResponseOfGetAllowedWorkflowsByUserResponseDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
