/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WithColumnItemRequestBuilder, WithColumnItemRequestBuilderRequestsMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /workflow/kanban-cards
 */
export interface KanbanCardsRequestBuilder extends BaseRequestBuilder<KanbanCardsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.workflow.kanbanCards.item collection
     * @param columnId Unique identifier of the item
     * @returns {WithColumnItemRequestBuilder}
     */
     byColumnId(columnId: string) : WithColumnItemRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const KanbanCardsRequestBuilderUriTemplate = "{+baseurl}/workflow/kanban-cards";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const KanbanCardsRequestBuilderNavigationMetadata: Record<Exclude<keyof KanbanCardsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byColumnId: {
        requestsMetadata: WithColumnItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["columnId"],
    },
};
/* tslint:enable */
/* eslint-enable */
