/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFastEndpointsErrorResponseFromDiscriminatorValue, createServerSharedModelsApiResponseOfAddHubResponseFromDiscriminatorValue, serializeServerSharedModelsApiResponseOfAddHubResponse, serializeServerSocialNetworkEndPointsHubsRequestsAddHubRequest, type FastEndpointsErrorResponse, type ServerSharedModelsApiResponseOfAddHubResponse, type ServerSocialNetworkEndPointsHubsRequestsAddHubRequest } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /hub/{platformId}
 */
export interface WithPlatformItemRequestBuilder extends BaseRequestBuilder<WithPlatformItemRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ServerSharedModelsApiResponseOfAddHubResponse>}
     * @throws {FastEndpointsErrorResponse} error when the service returns a 400 status code
     */
     post(body: ServerSocialNetworkEndPointsHubsRequestsAddHubRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ServerSharedModelsApiResponseOfAddHubResponse | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ServerSocialNetworkEndPointsHubsRequestsAddHubRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithPlatformItemRequestBuilderUriTemplate = "{+baseurl}/hub/{platformId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithPlatformItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: WithPlatformItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createFastEndpointsErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createServerSharedModelsApiResponseOfAddHubResponseFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeServerSocialNetworkEndPointsHubsRequestsAddHubRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
