/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type WebhooksRequestBuilder, WebhooksRequestBuilderNavigationMetadata } from './webhooks/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /simulator
 */
export interface SimulatorRequestBuilder extends BaseRequestBuilder<SimulatorRequestBuilder> {
    /**
     * The webhooks property
     */
    get webhooks(): WebhooksRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const SimulatorRequestBuilderUriTemplate = "{+baseurl}/simulator";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const SimulatorRequestBuilderNavigationMetadata: Record<Exclude<keyof SimulatorRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    webhooks: {
        navigationMetadata: WebhooksRequestBuilderNavigationMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
