/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFastEndpointsErrorResponseFromDiscriminatorValue, createServerSharedModelsApiResponseOfGetKanbanCardsByColumnIdResponseDtoFromDiscriminatorValue, type FastEndpointsErrorResponse, type ServerSharedModelsApiResponseOfGetKanbanCardsByColumnIdResponseDto } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /workflow/kanban-cards/{columnId}
 */
export interface WithColumnItemRequestBuilder extends BaseRequestBuilder<WithColumnItemRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ServerSharedModelsApiResponseOfGetKanbanCardsByColumnIdResponseDto>}
     * @throws {FastEndpointsErrorResponse} error when the service returns a 400 status code
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ServerSharedModelsApiResponseOfGetKanbanCardsByColumnIdResponseDto | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WithColumnItemRequestBuilderUriTemplate = "{+baseurl}/workflow/kanban-cards/{columnId}";
/**
 * Metadata for all the requests in the request builder.
 */
export const WithColumnItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: WithColumnItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createFastEndpointsErrorResponseFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "send",
        responseBodyFactory:  createServerSharedModelsApiResponseOfGetKanbanCardsByColumnIdResponseDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
