/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createServerNotificationContractsMessageDtosGetMessageResponseDtoFromDiscriminatorValue, serializeServerNotificationContractsMessageDtosGetMessageResponseDto, serializeServerNotificationContractsMessageQueriesGetMessageQuery, type ServerNotificationContractsMessageDtosGetMessageResponseDto, type ServerNotificationContractsMessageQueriesGetMessageQuery } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /hello/world
 */
export interface WorldRequestBuilder extends BaseRequestBuilder<WorldRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ServerNotificationContractsMessageDtosGetMessageResponseDto>}
     */
     post(body: ServerNotificationContractsMessageQueriesGetMessageQuery, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ServerNotificationContractsMessageDtosGetMessageResponseDto | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: ServerNotificationContractsMessageQueriesGetMessageQuery, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const WorldRequestBuilderUriTemplate = "{+baseurl}/hello/world";
/**
 * Metadata for all the requests in the request builder.
 */
export const WorldRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: WorldRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createServerNotificationContractsMessageDtosGetMessageResponseDtoFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeServerNotificationContractsMessageQueriesGetMessageQuery,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
