/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
export type ServerNotificationContractsMessageDtosGetMessageResponseDto = {
  text?: string;
};

export type ServerNotificationContractsMessageQueriesGetMessageQuery = {
  text?: string;
};

export type ServerSharedModelsApiResponseOfAddHubResponse = {
  isSuccess?: boolean;
  message?: string | null;
  data?: ServerSocialNetworkContractsHubsAddHubResponse | null;
  errors?: string[] | null;
  validationErrors?: string[] | null;
};

export type ServerSocialNetworkContractsHubsAddHubResponse = {
  id?: string;
};

/**
 * the dto used to send an error response to the client
 */
export type FastEndpointsErrorResponse = {
  /**
   * the http status code sent to the client. default is 400.
   *
   * @format int32
   * @default 400
   */
  statusCode?: number;
  /**
   * the message for the error response
   *
   * @default One or more errors occurred!
   */
  message?: string;
  /**
   * the collection of errors for the current context
   */
  errors?: {
    [key: string]: string[];
  };
};

export type ServerSocialNetworkEndPointsHubsRequestsAddHubRequest = {
  name?: string;
  phoneNumber?: string;
};

export type ServerSharedModelsApiResponseOfGetHubsResponse = {
  isSuccess?: boolean;
  message?: string | null;
  data?: ServerSocialNetworkContractsHubsGetHubsResponse | null;
  errors?: string[] | null;
  validationErrors?: string[] | null;
};

export type ServerSocialNetworkContractsHubsGetHubsResponse = {
  tenantId?: string;
  items?: ServerSocialNetworkContractsHubsHubItem[];
};

export type ServerSocialNetworkContractsHubsHubItem = {
  hubId?: string;
  platformId?: string;
  phoneNumber?: string;
  status?: string;
};

export type ServerSocialNetworkEndPointsHubsRequestsGetHubsRequest = Record<
  string,
  any
>;

export type ServerSocialNetworkSimulatorEndPointsWebHoooksMessageResponse = {
  status?: string;
};

export type ServerSocialNetworkSimulatorEndPointsWebHoooksMessageRequest = {
  message?: string;
};

export type ServerSharedModelsApiResponseOfAddWorkflowResponseDto = {
  isSuccess?: boolean;
  message?: string | null;
  data?: ServerWorkflowsContractsDtosAddWorkflowResponseDto | null;
  errors?: string[] | null;
  validationErrors?: string[] | null;
};

export type ServerWorkflowsContractsDtosAddWorkflowResponseDto = {
  id?: string;
};

export type ServerWorkflowsContractsCommandsAddWorkflowCommand = {
  name?: string;
  description?: string | null;
  columns?: ServerWorkflowsContractsDtosColumnItemDto[];
  tenantId?: string;
};

export type ServerWorkflowsContractsDtosColumnItemDto = {
  id?: string;
  /**
   * @format int32
   */
  positionIndex?: number;
  title?: string;
  description?: string;
};

export type ServerSharedModelsApiResponseOfAssignWorkflowToUserResponseDto = {
  isSuccess?: boolean;
  message?: string | null;
  data?: ServerWorkflowsContractsDtosAssignWorkflowToUserResponseDto | null;
  errors?: string[] | null;
  validationErrors?: string[] | null;
};

export type ServerWorkflowsContractsDtosAssignWorkflowToUserResponseDto = {
  result?: boolean;
};

export type ServerWorkflowsContractsCommandsAssignWorkflowToUserCommand = {
  userId?: string;
  workflowId?: string;
};

export type ServerSharedModelsApiResponseOfEditWorkflowResponseDto = {
  isSuccess?: boolean;
  message?: string | null;
  data?: ServerWorkflowsContractsDtosEditWorkflowResponseDto | null;
  errors?: string[] | null;
  validationErrors?: string[] | null;
};

export type ServerWorkflowsContractsDtosEditWorkflowResponseDto = {
  id?: string;
};

export type ServerWorkflowsContractsCommandsEditWorkflowCommand = {
  id?: string;
  name?: string;
  description?: string;
  columns?: ServerWorkflowsContractsDtosEditColumnItemDto[];
};

export type ServerWorkflowsContractsDtosEditColumnItemDto = {
  title?: string;
  id?: string | null;
  /**
   * @format int32
   */
  positionIndex?: number;
  description?: string;
};

export type ServerSharedModelsApiResponseOfGetAllowedWorkflowsByUserResponseDto =
  {
    isSuccess?: boolean;
    message?: string | null;
    data?: ServerWorkflowsContractsDtosGetAllowedWorkflowsByUserResponseDto | null;
    errors?: string[] | null;
    validationErrors?: string[] | null;
  };

export type ServerWorkflowsContractsDtosGetAllowedWorkflowsByUserResponseDto = {
  allowedWorkflows?: ServerWorkflowsContractsDtosAllowedWorkflowDto[];
};

export type ServerWorkflowsContractsDtosAllowedWorkflowDto = {
  id?: string;
  name?: string;
  description?: string;
};

export type ServerSharedModelsApiResponseOfGetKanbanCardsByColumnIdResponseDto =
  {
    isSuccess?: boolean;
    message?: string | null;
    data?: ServerWorkflowsContractsDtosGetKanbanCardsByColumnIdResponseDto | null;
    errors?: string[] | null;
    validationErrors?: string[] | null;
  };

export type ServerWorkflowsContractsDtosGetKanbanCardsByColumnIdResponseDto = {
  kanbanCards?: ServerWorkflowsContractsCardsKanbanCardDto[];
};

export type ServerWorkflowsContractsCardsKanbanCardDto = {
  id?: string;
  content?: ServerWorkflowsContractsCardsCardContentTypesICardContentType;
  columnId?: string;
};

/**
 * @x-abstract true
 */
export type ServerWorkflowsContractsCardsCardContentTypesICardContentType = {
  contentType?: string;
  hubId?: string;
  platformId?: string;
};

export type ServerSharedModelsApiResponseOfGetWorkflowByIdResponseDto = {
  isSuccess?: boolean;
  message?: string | null;
  data?: ServerWorkflowsContractsDtosGetWorkflowByIdResponseDto | null;
  errors?: string[] | null;
  validationErrors?: string[] | null;
};

export type ServerWorkflowsContractsDtosGetWorkflowByIdResponseDto = {
  id?: string;
  title?: string;
  description?: string;
  columns?: ServerWorkflowsContractsDtosColumnItemResponseDto[];
};

export type ServerWorkflowsContractsDtosColumnItemResponseDto = {
  id?: string;
  title?: string;
  description?: string;
  /**
   * @format int32
   */
  positionIndex?: number;
};

export type ServerWorkflowsContractsQueriesGetWorkflowByIdQuery = Record<
  string,
  any
>;

export type ServerSharedModelsApiResponseOfGetWorkflowsResponseDto = {
  isSuccess?: boolean;
  message?: string | null;
  data?: ServerWorkflowsContractsDtosGetWorkflowsResponseDto | null;
  errors?: string[] | null;
  validationErrors?: string[] | null;
};

export type ServerWorkflowsContractsDtosGetWorkflowsResponseDto = {
  workflows?: ServerWorkflowsContractsDtosWorkflowDto[];
};

export type ServerWorkflowsContractsDtosWorkflowDto = {
  id?: string;
  name?: string;
  description?: string;
  columns?: ServerWorkflowsContractsDtosWorkflowColumnDto[];
};

export type ServerWorkflowsContractsDtosWorkflowColumnDto = {
  id?: string;
  title?: string;
  description?: string;
  /**
   * @format int32
   */
  positionIndex?: number;
};
